#!/bin/sh

BASE_DIR=$1
shift
ARCH=$1
shift
PACKAGES=$@

for PACKAGE in $PACKAGES; do
	FILES=$(ls $BASE_DIR/$ARCH/$PACKAGE)
	echo "INSTALLING $FILES"
	for FILE in $FILES; do
		apk add --allow-untrusted $FILE
	done
done
