#!/bin/sh

echo $(pwd)
mv -f *.tar.bz2 ./alpine
PACKAGER_PRIVKEY=/abuild/abuild.rsa
cd alpine
abuild checksum
JOBS=$(expr $(nproc) / 2) SRCDEST=$(pwd) REPODEST=/localrepo PACKAGER_PRIVKEY=$PACKAGER_PRIVKEY abuild -ri
